// ============================================================
//
// Terrain shaders for frostbite_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'surfaceparm nolightmap' from terrain shaders
//   and added lightmap stages, to allow the terrain to be lightmapped
// - added base shader, which sets up lightmapping
//
// ============================================================

textures/frostbite_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

// fix for terrain blending near side gate,
// due to chopped up terrain geometry
textures/frostbite_source_rebuild/alpha_050
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.5

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/frostbite_source_rebuild/terrain_base
{
	q3map_terrain

	q3map_lightmapMergable
	q3map_lightmapaxis z
}

textures/frostbite_source_rebuild/terrain_0
{
	surfaceparm snowsteps
//	q3map_novertexshadows
//	q3map_forcesunlight	
	q3map_baseshader textures/frostbite_source_rebuild/terrain_base
	q3map_texturesize 512 512
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	{
		map textures/frostbite/night_lightsnow.tga
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	surfaceparm landmine	
}

textures/frostbite_source_rebuild/terrain_1
{
	surfaceparm snowsteps
//	q3map_novertexshadows
//	q3map_forcesunlight	
	q3map_baseshader textures/frostbite_source_rebuild/terrain_base
	q3map_texturesize 512 512
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	{
		map textures/frostbite/night_darksnow.tga
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	surfaceparm landmine	
}

textures/frostbite_source_rebuild/terrain_0to1
{
	surfaceparm snowsteps
//	q3map_novertexshadows
//	q3map_forcesunlight	
	q3map_baseshader textures/frostbite_source_rebuild/terrain_base
	q3map_texturesize 512 512
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	{
		map textures/frostbite/night_lightsnow.tga
		rgbGen identity
		alphaGen vertex
	}
	{
		map textures/frostbite/night_darksnow.tga
		rgbGen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	surfaceparm landmine	
}
