// ============================================================
//
// Shaders for karsiah_te2_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'sand'
//   to allow higher resolution lightmaps
//
// ============================================================

// fixed version of stock blitz window shader, with corrected
// 'rgbGen' directive to make the windows work with 'misc_model'
textures/karsiah_te2_source_rebuild/blitz_sd_windows_mm
{
	qer_editorimage models/mapobjects/blitz_sd/blitz_sd.tga
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/mapobjects/blitz_sd/blitz_sd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

textures/karsiah_te2_source_rebuild/sand 
{ 
	qer_editorimage textures/karsiah/sand.tga
q3map_nonplanar 
q3map_shadeangle 100 
surfaceparm gravelsteps 
surfaceparm landmine 
q3map_lightmapMergable 
implicitMap textures/karsiah/sand.tga
}
