// ============================================================
//
// Shaders for venice_source_rebuild.map
// https://github.com/aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'courtyard_brick2'
//   to allow for higher resolution lightmaps
//
// ============================================================

// fixed version of stock blitz window shader, with corrected
// 'rgbgen' directive to make the windows work with 'misc_model'
textures/venice_source_rebuild/blitz_sd_windows_mm
{
	qer_editorimage models/mapobjects/blitz_sd/blitz_sd.tga
	{
		map textures/effects/envmap_slate.tga
		rgbgen lightingdiffuse
		tcgen environment
	}
	{
		map models/mapobjects/blitz_sd/blitz_sd.tga
		blendfunc gl_one gl_one_minus_src_alpha
		rgbgen environment
	}
}

textures/venice_source_rebuild/courtyard_brick2
{
	qer_editorimage textures/venice_floor_c1/courtyard_brick2.tga
	q3map_splotchfix
	q3map_nonplanar
	q3map_shadeangle 120
//	q3map_tcGen ivector ( 128 0 0 ) ( 0 128 0 )
	implicitMap textures/venice_floor_c1/courtyard_brick2.tga

}
