// ============================================================
//
// Terrain shaders for snatch3_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed original 'qer_editorimage' directives
//
// ============================================================

textures/snatch3_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/snatch3_source_rebuild/terrain_base
{
	q3map_terrain

	q3map_lightmapaxis z
	q3map_lightmapmergable
	q3map_tcMod rotate 33
	q3map_tcGen ivector ( 256 0 0 ) ( 0 256 0 )
	nopicmip
}

textures/snatch3_source_rebuild/terrain_baseb
{
	q3map_terrain

	q3map_lightmapaxis z
	q3map_lightmapmergable
	q3map_tcMod rotate 33
	q3map_tcGen ivector ( 256 0 0 ) ( 0 256 0 )
	nopicmip
}

textures/snatch3_source_rebuild/terrain_0
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb
	{
		map textures/snatch3/snatchgrass.tga
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm landmine
	surfaceparm grasssteps	
}

textures/snatch3_source_rebuild/terrain_1
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_base	
	{
		map textures/temperate_sd/rock_grayvar.tga
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

textures/snatch3_source_rebuild/terrain_2
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb
	
	{

		map textures/snatch3/snatchdgrass.tga
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm landmine
	surfaceparm grasssteps
}


textures/snatch3_source_rebuild/terrain_3
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_base	

	{
		map textures/temperate_sd/rock_ugly_brown.tga
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

textures/snatch3_source_rebuild/terrain_4
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	{
		map textures/snatch3/gravel.jpg
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm landmine
	surfaceparm gravelsteps
}

textures/snatch3_source_rebuild/terrain_0to1
{
	q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/snatch3/snatchgrass.tga
	}
	{
		map textures/temperate_sd/rock_grayvar.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm grasssteps
}

textures/snatch3_source_rebuild/terrain_0to2
{

    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	{
		map textures/snatch3/snatchgrass.tga
	}
	{
		map textures/snatch3/snatchdgrass.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm landmine
	surfaceparm grasssteps
}

textures/snatch3_source_rebuild/terrain_0to3
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/snatch3/snatchgrass.tga
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm grasssteps	
}

textures/snatch3_source_rebuild/terrain_0to4
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/snatch3/snatchgrass.tga
	}
	{
		map textures/snatch3/gravel.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm grasssteps	
}

textures/snatch3_source_rebuild/terrain_1to2
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/temperate_sd/rock_grayvar.tga
	}
	{
		map textures/snatch3/snatchdgrass.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm landmine
	surfaceparm grasssteps
}

textures/snatch3_source_rebuild/terrain_1to3
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_base	
	
	{
		map textures/temperate_sd/rock_grayvar.tga
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

textures/snatch3_source_rebuild/terrain_1to4
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_base	
	
	{
		map textures/temperate_sd/rock_grayvar.tga
	}
	{
		map textures/snatch3/gravel.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

textures/snatch3_source_rebuild/terrain_2to3
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/snatch3/snatchdgrass.tga
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm grasssteps	
}

textures/snatch3_source_rebuild/terrain_2to4
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_baseb	
	
	{
		map textures/snatch3/snatchdgrass.tga
	}
	{
		map textures/snatch3/gravel.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	surfaceparm grasssteps	
}

textures/snatch3_source_rebuild/terrain_3to4
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_base	
	{
		map textures/temperate_sd/rock_ugly_brown.tga
	}
	{
		map textures/snatch3/gravel.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

// reversed 3to4
textures/snatch3_source_rebuild/terrain_4to3
{
    q3map_baseshader textures/snatch3_source_rebuild/terrain_base	
	{
		map textures/snatch3/gravel.jpg
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
}
