// ============================================================
//
// Terrain shaders for warbell_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_tcMod scale' from all shaders
//   where applicable, to not perform scaling twice
//
// ============================================================

textures/warbell_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_025
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.25

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_050
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.5

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_053
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.53

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_065
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.65

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_075
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.75

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_085
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.85

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/alpha_100
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 1.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/warbell_source_rebuild/wb_wax1
{
	qer_editorimage textures/wb_p/wb_wax1.jpg

	q3map_nonplanar
	q3map_shadeangle 180

	surfaceparm nomarks
	surfaceparm nonsolid	

	implicitMap textures/wb_p/wb_wax1.jpg
}

textures/warbell_source_rebuild/ei_terrain_grass
{
	qer_editorimage textures/wb_ei/ei_terrain_grass.jpg
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm grasssteps
	surfaceparm landmine
	implicitMap textures/temperate_sd/grass_dense1.tga
}

textures/warbell_source_rebuild/ei_terrain_rock1
{
	qer_editorimage textures/wb_ei/ei_terrain_rock1.jpg
	q3map_nonplanar
	q3map_shadeangle 120
	implicitMap textures/wb_t/wb_rock01.jpg // temperate_sd/rock_ugly_brown.tga
}

// ---------------------------------------------
// ------------ WATER --------------------------
// ---------------------------------------------


textures/warbell_source_rebuild/complex
{
	qer_editorimage textures/wb_t/complex.jpg
	q3map_nonplanar
	qer_trans 0.7

	q3map_globaltexture //new

	surfaceparm water
	surfaceparm trans // added...
	surfaceparm nomarks

	cull disable // "back" is no good idea
	deformVertexes wave 160 sin 0 10 0 .3	// the chop, removed for causing split with slope water
	// implicitMap textures/wb_t/wb_water_02_d03.tga


	{ 
		map textures/wb_t/complex.jpg
		rgbgen identity
		tcmod scroll 0 -.05		// paused
	}

	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// added
		rgbgen wave sin .4 0 0 .5
		alphaGen vertex							// added
		tcmod scale .7 .7		// paused
		// tcmod scroll .03 .02	
		tcmod scroll 0 -.2		// paused
		depthWrite			// try to avoid the funny effect with smoke etc
	}	

	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_src_alpha GL_ONE // gl_zero_minus_src_alpha invalid
		alphagen const .25		
		tcmod scale .2 .2
		// tcmod scroll -.03 -.02	
		tcmod scroll 0 .01
	}

	{ 
		map $lightmap
		blendfunc filter
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA
		rgbGen identity
		// alphaGen vertex
	}
}

// make the second water with the alpha gen for the foam instead of darker water
// act as the wedge to seperate light edge water and foamy water as no alpha brushes are needed

textures/warbell_source_rebuild/wedge
{
	qer_editorimage textures/wb_t/wedge.jpg
	q3map_nonplanar
	qer_trans 0.7

	q3map_globaltexture //new

	surfaceparm water
	surfaceparm trans // added...
	surfaceparm nomarks

	cull disable // "back" is no good idea
	deformVertexes wave 160 sin 0 10 0 .3	// the chop, removed for causing split with slope water
	// implicitMap textures/wb_t/wb_water_02_d03.tga

	{ 
		map textures/wb_t/complex.jpg
		// blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// added
		rgbgen wave sin .4 0 0 .5
		// alphaGen vertex							// no in this shader
		// alphagen const 1			// to  fake the 100 alpha values
		tcmod scale .7 .7		// paused
		// tcmod scroll .03 .02	
		tcmod scroll 0 -.2		// paused
		depthWrite			// try to avoid the funny effect with smoke etc
	}	

	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_src_alpha GL_ONE // gl_zero_minus_src_alpha invalid
		alphagen const .25		
		tcmod scale .2 .2
		// tcmod scroll -.03 -.02	
		tcmod scroll 0 .01
	}

	{ 
		map $lightmap
		blendfunc filter
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA
		rgbGen identity
		// alphaGen vertex
	}
}

// the third water shader for the water with foam on top

textures/warbell_source_rebuild/waterfoam
{
	qer_editorimage textures/wb_t/waterfoam.tga
	q3map_nonplanar
	qer_trans 0.7

	q3map_globaltexture //new

	surfaceparm water
	surfaceparm trans // added...
	surfaceparm nomarks

	cull disable // front
	deformVertexes wave 160 sin 0 10 0 .3	// the chop, removed for causing split with slope water
	// implicitMap textures/wb_t/wb_water_02_d03.tga

	{ 
		map textures/wb_t/complex.jpg
		// blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// added
		rgbgen wave sin .4 0 0 .5
		// alphaGen vertex							// no in this shader
		// alphagen const 1			// to  fake the 100 alpha values
		tcmod scale .7 .7		// paused
		// tcmod scroll .03 .02	
		tcmod scroll 0 -.2		// paused
		depthWrite			// try to avoid the funny effect with smoke etc
	}	

	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_src_alpha GL_ONE // gl_zero_minus_src_alpha invalid
		alphagen const .25		
		tcmod scale .2 .2
		// tcmod scroll -.03 -.02	
		tcmod scroll 0 .01
	}

	{
		map textures/wb_t/waterfoam.tga	// the foam image
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// transparency for alpha brushes
		alphaGen vertex		// generate alpha values from alpha brushes
		tcmod scroll 0 -.55
		alphaFunc GE128
	}

	{ 
		map $lightmap
		blendfunc filter
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA
		rgbGen identity
		// alphaGen vertex
	}
}


// calm foam, needed to close the gap at the disappearing waterfall

textures/warbell_source_rebuild/waterfoamcalm
{
	qer_editorimage textures/wb_t/waterfoam.tga

	q3map_nonplanar
	q3map_shadeangle 180

	qer_trans 0.7

	q3map_globaltexture //new

	surfaceparm water
	surfaceparm trans // added...
	surfaceparm nomarks
	//surfaceparm alphashadow		//try to make it darker under the water so it looks more beliavble when submerged

	cull disable // front
	//deformVertexes wave 80 sin 0 3 0 0.3 // 160 sin 0 10 0 .3 the chop, removed for causing split with slope water
	
	{ 
		map textures/wb_t/complex.jpg
		// blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// added
		rgbgen wave sin .4 0 0 .5
		// alphaGen vertex							// no in this shader
		// alphagen const 1			// to  fake the 100 alpha values
		tcmod scale .7 .7		// paused
		// tcmod scroll .03 .02	
		tcmod scroll 0 -.2		// paused
		depthWrite			// try to avoid the funny effect with smoke etc
	}	

	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_src_alpha GL_ONE // gl_zero_minus_src_alpha invalid
		alphagen const .25	
		tcmod scale .2 .2
		// tcmod scroll -.03 -.02	
		tcmod scroll 0 .01
	}

	{
		map textures/wb_t/waterfoam.tga	// the foam image
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// transparency for alpha brushes
		alphaGen vertex		// generate alpha values from alpha brushes
		tcmod scroll 0 -.55
		alphaFunc GE128
	}

	{ 
		map $lightmap
		blendfunc filter
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA
		rgbGen identity
		// alphaGen vertex
	}
}


textures/warbell_source_rebuild/wb_waterfall //carnmcnite/fall 
{ 
	qer_editorimage textures/wb_ei/ei_wb_waterfall.tga 
	q3map_nonplanar 
	q3map_shadeangle 120 
	qer_trans 0.7 

	q3map_globaltexture //new 
	q3map_tcGen ivector ( 256 0 0 ) ( 0 0 -256 ) // 1/256 = 0.00390625 

	surfaceparm water 
	surfaceparm trans // added... 
	surfaceparm nomarks 

	cull disable // "back" is no good idea 

	{ 
		map textures/wb_t/wb_waterfall.tga  // textures/wb_t/complex.jpg 
		// blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA // added 
		rgbgen wave sin .4 0 0 .5 
		// alphaGen vertex // no in this shader 
		// alphagen const 0.25 // to  fake the 100 alpha values 
		tcmod scale .7 .7 // paused 
		tcmod scroll 0 -0.5 // 0 -1
		depthWrite // try to avoid the funny effect with smoke etc 
	} 
	
	{ 
		map textures/wb_t/wb_waterfall.tga // the foam image 
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA // transparency for alpha brushes 
		alphaGen vertex // generate alpha values from alpha brushes 
		tcmod scroll 0 -0.75 // 0 -1.5 
		// alphaFunc GE128 
	} 

	{ 
		map $lightmap 
		blendfunc filter 
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA 
		rgbGen identity 
		// alphaGen vertex 
	} 
} 

textures/warbell_source_rebuild/wb_watercalm // shader written by carnage
{
	qer_editorimage textures/wb_t/complex.jpg
	q3map_nonplanar
	qer_trans 0.7

	q3map_globaltexture //new

	surfaceparm water
	surfaceparm trans // added...
	surfaceparm nomarks

	cull disable // "back" is no good idea
	deformVertexes wave 160 sin 0 2 0 .3	// the chop, removed for causing split with slope water
	// implicitMap textures/wb_t/wb_water_02_d03.tga



	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA		// added
		rgbgen wave sin .4 0 0 .5
		alphaGen vertex							// added
		tcmod scale .7 .7		// paused
		tcmod scroll -.03 -.02	
		//tcmod scroll 0 -.2		// paused
		depthWrite			// try to avoid the funny effect with smoke etc
	}	
	{ 
		map textures/wb_t/complex.jpg
		blendFunc GL_src_alpha GL_ONE // gl_zero_minus_src_alpha invalid
		alphagen const .25		
		tcmod scale .2 .2
		tcmod scroll .03 .02	
		//tcmod scroll 0 .01
	}
	{ 
		map $lightmap
		blendfunc filter
		// blendfunc GL_DST_COLOR GL_SRC_ALPHA
		rgbGen identity
		// alphaGen vertex
	}

}

// ---------------------------------------------------------------------------------------------
// ------------ PURE TEXTURES ------------------------------------------------------------------
// ---------------------------------------------------------------------------------------------

textures/warbell_source_rebuild/wb_pavement
{
	qer_editorimage textures/wb_z/ground_c06.jpg
	implicitMap textures/wb_z/ground_c06.jpg
}

textures/warbell_source_rebuild/wb_rock01
{
	qer_editorimage textures/wb_t/wb_rock01.jpg
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/wb_t/wb_rock01.tga
}

textures/warbell_source_rebuild/wb_riverbed1
{
	qer_editorimage textures/stone/mxrock3_a.jpg
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm gravelsteps
	implicitMap textures/stone/mxrock3_a.jpg
}

textures/warbell_source_rebuild/wb_grass
{
	qer_editorimage textures/temperate_sd/grass_dense1.tga
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm grasssteps
	surfaceparm landmine
	implicitMap textures/temperate_sd/grass_dense1.tga
}

textures/warbell_source_rebuild/wb_gravel
{
	qer_editorimage textures/temperate_sd/dirt3.tga  //sand_patchnoise.tga
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm gravelsteps
	surfaceparm landmine
	implicitMap textures/temperate_sd/dirt3.tga //sand_patchnoise.tga
}

textures/warbell_source_rebuild/wb_path
{
	qer_editorimage textures/wb_t/wb_path.jpg  //sand_patchnoise.tga
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm gravelsteps
	surfaceparm landmine
	implicitMap textures/wb_t/wb_path.jpg //sand_patchnoise.tga
}

textures/warbell_source_rebuild/wb_road
{
	qer_editorimage textures/wb_t/wb_road.jpg
	q3map_nonplanar
	q3map_shadeangle 100
	surfaceparm gravelsteps
	surfaceparm landmine
	implicitMap textures/wb_t/wb_road.jpg
}


// ---------------------------------------------------------------------------------------------
// ------------ CAVE SHADERS AND ALPHA BLENDS --------------------------------------------------
// ---------------------------------------------------------------------------------------------


textures/warbell_source_rebuild/wb_cavesand
{
	qer_editorimage textures/temperate_sd/sand_patchnoise.tga
	//qer_editorimage textures/wb_t/wb_gravel2.jpg
	q3map_nonplanar
	q3map_shadeangle 180
	surfaceparm gravelsteps
	implicitMap textures/temperate_sd/sand_patchnoise.tga
}

textures/warbell_source_rebuild/wb_caverock1
{
	qer_editorimage textures/stone/mxrock3_a.tga
	q3map_nonplanar
	q3map_shadeangle 100
	implicitMap textures/stone/mxrock3_a.tga
}

// ---------------------------------------------
// ------------ OTHER TERRAIN SHADERS ----------
// ---------------------------------------------



textures/warbell_source_rebuild/wb_singlerock01
{
	qer_editorimage models/mapobjects/rocks_sd/rock_temperate_big.jpg
	q3map_clipModel
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap models/mapobjects/rocks_sd/rock_temperate_big.jpg
}

textures/warbell_source_rebuild/wb_singlerock02
{
	qer_editorimage models/mapobjects/rocks_sd/rock_temperate2_big.jpg
	q3map_clipModel
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap models/mapobjects/rocks_sd/rock_temperate2_big.jpg
}

textures/warbell_source_rebuild/wb_singlerock03
{
	qer_editorimage textures/wb_t/wb_rock01.jpg
	q3map_clipModel
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap textures/wb_t/wb_rock01.jpg
}
