// ============================================================
//
// Shaders for et_ufo_final_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
// - added 'q3map_terrain' to 'terrain_base' to inherit the
//   properties of the terrain meta shader used in the original map
// - removed original 'qer_editorimage' directives from
//   terrain shader in favor of custom images
//
// ============================================================

textures/et_ufo_final_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/et_ufo_final_source_rebuild/terrain_base
{
	qer_editorimage textures/common/terrain.tga
	q3map_normalimage textures/sd_bumpmaps/normalmap_terrain.tga

	q3map_terrain

	q3map_nonplanar 
	q3map_shadeangle 90 

	q3map_lightmapMergable
	q3map_lightmapaxis z

	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	q3map_tcMod scale 2 2
	q3map_tcMod rotate 37

	surfaceparm grasssteps
}

textures/et_ufo_final_source_rebuild/terrain_0
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base

	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_1
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base

	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_2
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base

	{
		map textures/stone/mxrock3_a.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_3
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base

	{
		map textures/temperate_sd/dirt3.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_0to1
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_0to2
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/stone/mxrock3_a.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_0to3
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_1to2
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		map textures/stone/mxrock3_a.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_1to3
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/et_ufo_final_source_rebuild/terrain_2to3
{
	q3map_baseshader textures/et_ufo_final_source_rebuild/terrain_base
	
	{
		map textures/stone/mxrock3_a.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}
