// ============================================================
//
// Shaders for et_beach_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'surfaceparm nolightmap' from terrain shaders
//   and added lightmap stages, to allow the terrain to be lightmapped
// - removed obsolete 'q3map_noVertexShadows' and 'q3map_forceSunlight'
//   from terrain shaders (these make no sense with lightmapped terrain)
// - added base shader, which sets up lightmapping
// - removed 'tcMod scale' stage directive from shaders in favor of
//   'q3map_tcMod scale' on the base shader for compile-time scaling
//
// ============================================================

textures/et_beach_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/et_beach_source_rebuild/terrain_base
{
	qer_editorimage textures/common/terrain.tga
	q3map_terrain
	q3map_tcMod scale 0.083 0.083
	q3map_lightmapMergable
	q3map_lightmapaxis z
}

textures/et_beach_source_rebuild/terrain_0
{
	q3map_baseshader textures/et_beach_source_rebuild/terrain_base
	{
		map textures/stone/mxrock12c.jpg
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/et_beach_source_rebuild/terrain_1
{
	q3map_baseshader textures/et_beach_source_rebuild/terrain_base
	{
		map textures/desert_sd/sand_patchy.tga
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/et_beach_source_rebuild/terrain_0to1
{
	q3map_baseshader textures/et_beach_source_rebuild/terrain_base
	{
		map textures/stone/mxrock12c.jpg
		rgbGen identity
		alphaGen vertex
	}
	{
		map textures/desert_sd/sand_patchy.tga
		rgbGen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}
