// ============================================================
//
// Terrain shaders for goldrush_terrain_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
// - added some special shaders to work around modern face splitting
//   algorithms - 'q3map_noTJunc' is used in some shaders to prevent
//   terrain brush faces from getting split up
//
// ============================================================

textures/goldrush_terrain_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

// used to fix terrain blending at the back corner of the bank back alley
textures/goldrush_terrain_rebuild/alpha_025
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

// steps near truck exit, 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/mat_wall1
{
	qer_editorimage textures/egypt_walls_sd/mat_wall1.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/mat_wall1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// corner near Axis 2nd spawn back exit leading to bank back alley
// and fake door at the last tank path bend,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/trim_c03b
{
	qer_editorimage textures/egypt_trim_sd/trim_c03b.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_trim_sd/trim_c03b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// corner near Axis 2nd spawn main exit,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/tobruk_wall_base9
{
	qer_editorimage textures/tobruk_wall_sd/tobruk_wall_base9.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/tobruk_wall_sd/tobruk_wall_base9.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// wooden plank near the stairs leading to MG42 nest near tank barrier #2,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/wood_c13
{
	qer_editorimage textures/egypt_floor_sd/wood_c13.tga
	q3map_noTJunc
	surfaceparm woodsteps
	implicitMap textures/egypt_floor_sd/wood_c13.tga
}

// trim at the start of the steps leading to MG42 nest near tank barrier #2,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/roughbrick01
{
	qer_editorimage textures/egypt_walls_sd/roughbrick01.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/roughbrick01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// pillars at the bank entrance staircase,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/stucco01
{
	qer_editorimage textures/egypt_walls_sd/stucco01.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/stucco01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// side wall of the staircase at the bank entrance,
// 'q3map_noTJunc' added to fix terrain blending
textures/goldrush_terrain_rebuild/stucco01_decor01
{
	qer_editorimage textures/egypt_walls_sd/stucco01_decor01.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/stucco01_decor01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/goldrush_terrain_rebuild/terrain_base
{
	q3map_lightmapaxis z
	q3map_lightmapmergable
	q3map_tcGen ivector ( 299 0 0 ) ( 0 299 0 )
}

textures/goldrush_terrain_rebuild/terrain_0
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/temperate_sd/sand_bubbles_bright.tga
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_0to1
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/temperate_sd/sand_bubbles_bright.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/pavement_quad_sandy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_0to2
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/temperate_sd/sand_bubbles_bright.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/pavement_tris_sandy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_0to3
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	surfaceparm gravelsteps
	surfaceparm landmine
	{
		map textures/temperate_sd/sand_bubbles_bright.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/road_dirty_gravel.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_1
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_quad_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_1to2
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_quad_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/pavement_tris_sandy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_1to3
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_quad_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/road_dirty_gravel.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_2
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_tris_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_2to3
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_tris_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/desert_sd/road_dirty_gravel.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

textures/goldrush_terrain_rebuild/terrain_3
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	surfaceparm gravelsteps
	surfaceparm landmine
	{
		map textures/desert_sd/road_dirty_gravel.tga
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}

// reversed 0to1
textures/goldrush_terrain_rebuild/terrain_1to0
{
	q3map_baseshader textures/goldrush_terrain_rebuild/terrain_base
	{
		map textures/desert_sd/pavement_quad_sandy.tga
		tcMod scale 1.75 1.75
	}
	{
		map textures/temperate_sd/sand_bubbles_bright.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
		tcMod scale 1.75 1.75
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		tcMod scale 3 3
		detail
	}
}
