// ============================================================
//
// Terrain shaders for caen2_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
// - removed 'q3map_lightmapsamplesize 16' from 'terrain_base'
//   to allow any samplesize value for terrain
// - removed original 'qer_editorimage' directive from
//   'terrain_0' shader in favor of custom image
//
// ============================================================

textures/caen2_source_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

//TERRAIN//==============================================================================

textures/caen2_source_rebuild/terrain_base
{
	q3map_tcGen ivector ( 256 0 0 ) ( 0 256 0 )
	q3map_lightmapMergable
	q3map_lightmapaxis z
	q3map_shadeangle 179
}

textures/caen2_source_rebuild/terrain_0
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm grasssteps
	
	{

		map textures/temperate_sd/grass_dense1.tga
                
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_1
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	
	{

		map textures/desert_sd/road_dirty_gravel.tga
                
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_2
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	
	{

		map textures/temperate_sd/dirt3.tga
                
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_3
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	
	surfaceparm gravelsteps
	
	{

		map textures/stone/mxrock1aa.tga
                
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_0to1
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
                
		
	}
	{
		map textures/desert_sd/road_dirty_gravel.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_0to2
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
                
		
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_0to3
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
                
		
	}
	{
		map textures/stone/mxrock1aa.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_1to2
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/desert_sd/road_dirty_gravel.tga
		alphaGen vertex
                
		
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_1to3
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/desert_sd/road_dirty_gravel.tga
		alphaGen vertex
                
		
	}
	{
		map textures/stone/mxrock1aa.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

textures/caen2_source_rebuild/terrain_2to3
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
               
		
	}
	{
		map textures/stone/mxrock1aa.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}

// reversed 2to3
textures/caen2_source_rebuild/terrain_3to2
{
	q3map_baseshader textures/caen2_source_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	{
		map textures/stone/mxrock1aa.tga
		alphaGen vertex
               
		
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
                
	}
	
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcmod scale 4 4
	}
}
