// ============================================================
//
// Terrain shaders for oasis_terrain_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
// - removed 'q3map_lightmapsamplesize 16' from 'terrain_base'
//   to allow any samplesize value for terrain
// - added some special shaders to work around modern face splitting
//   algorithms - 'q3map_noTJunc' is used in some shaders to prevent
//   terrain brush faces from getting split up
//
// ============================================================

textures/oasis_terrain_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

// gate near the anti-tank guns
// 'q3map_noTJunc' added to fix terrain blending
textures/oasis_terrain_rebuild/mesh_c02_clipmissle
{
	qer_trans 0.85
	qer_editorimage textures/alpha/mesh_c02.tga
	q3map_noTJunc
	cull disable
	nomipmaps
	nopicmip

	surfaceparm clipmissile
	surfaceparm nomarks
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans

	implicitMask textures/alpha/mesh_c02.tga
}

textures/oasis_terrain_rebuild/terrain_base
{
	q3map_tcGen ivector ( 256 0 0 ) ( 0 256 0 )
	q3map_lightmapMergable
	q3map_lightmapaxis z
	q3map_shadeangle 179
	
}

textures/oasis_terrain_rebuild/terrain_0
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_3
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_4
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
		 
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to1
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to2
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to3
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to4
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_0to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_wave_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to2
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to3
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to4
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_1to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_sand_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2to3
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2to4
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2to5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_2to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_patchy.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_3to4
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_3to5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_3to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_3to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/sand_disturb_desert.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_4to5
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_4to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_4to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/grass_desert_flat.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_5to6
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_5to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	 
	 
	
	{
		map textures/desert_sd/rock_edged_smooth.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}

textures/oasis_terrain_rebuild/terrain_6to7
{
	q3map_baseshader textures/oasis_terrain_rebuild/terrain_base
	surfaceparm landmine
	surfaceparm gravelsteps
	
	{
		map textures/desert_sd/sand_gravels_bright.tga
		rgbgen identity
	}
	{
		map textures/desert_sd/sand_dirt_medium.tga
		rgbgen identity
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		 
	}
	{
		map textures/detail_sd/sanddetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		detail
		tcMod scale 6 6
	}
}
