// ============================================================
//
// Terrain shaders for radar_terrain_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
// - removed 'terrain2_5' and any '*to5' shaders as they
//   are not used in the map, and the texture doesn't exist
// - added some special shaders to work around modern face splitting
//   algorithms - 'q3map_noTJunc' is used in some shaders to prevent
//   terrain brush faces from getting split up
//
// ============================================================

textures/radar_terrain_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

// Forward bunker main entrance roof,
// 'q3map_noTJunc' added to fix terrain blending
textures/radar_terrain_rebuild/gy_ml03a_wet
{
	qer_editorimage textures/graveyard/gy_ml03a.tga
	q3map_noTJunc
	implicitMap textures/graveyard/gy_ml03a.tga
}

// Forward bunker main entrance roof edges,
// 'q3map_noTJunc' added to fix terrain blending
textures/radar_terrain_rebuild/gy_ml03a
{
	qer_editorimage textures/graveyard/gy_ml03a.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/graveyard/gy_ml03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

// Various pieces of wall structures in 2nd stage
// 'q3map_noTJunc' added to fix terrain blending
textures/radar_terrain_rebuild/wall_c03d
{
	qer_editorimage textures/broken_castle/wall_c03d.tga

	q3map_noTJunc
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/broken_castle/wall_c03d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/radar_terrain_rebuild/terrain2_base
{
	q3map_normalimage textures/sd_bumpmaps/normalmap_terrain.tga
	
	q3map_lightmapMergable
	q3map_lightmapaxis z
	
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	q3map_tcMod scale 2 2
	q3map_tcMod rotate 37
	
	surfaceparm grasssteps
	surfaceparm landmine
}

textures/radar_terrain_rebuild/terrain2_foliage_base
{
	q3map_baseShader textures/radar_terrain_rebuild/terrain2_base

	q3map_foliage models/foliage/grassfoliage1.md3 1.25 48 0.1 2
	q3map_foliage models/foliage/grassfoliage2.md3 1.1 48 0.1 2
	q3map_foliage models/foliage/grassfoliage3.md3 1 48 0.1 2
}

textures/radar_terrain_rebuild/terrain2_foliage_fade
{
	q3map_baseShader textures/radar_terrain_rebuild/terrain2_base

	q3map_foliage models/foliage/grassfoliage1.md3 1.25 64 0.1 2
	q3map_foliage models/foliage/grassfoliage2.md3 1.1 64 0.1 2
	q3map_foliage models/foliage/grassfoliage3.md3 1 64 0.1 2
}

textures/radar_terrain_rebuild/terrain2_0
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base

	{
		map textures/temperate_sd/master_grass_dirt3.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_1
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_base

	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_2
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base

	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_3
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base

	{
		map textures/temperate_sd/rock_ugly_brown.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_4
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base

	{
		map textures/temperate_sd/dirt3.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_0to1
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_fade

	{
		map textures/temperate_sd/master_grass_dirt3.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/grass_path1.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_0to2
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base

	{
		map textures/temperate_sd/master_grass_dirt3.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_0to3
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base
	
	{
		map textures/temperate_sd/master_grass_dirt3.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_0to4
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base
	
	{
		map textures/temperate_sd/master_grass_dirt3.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_1to2
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/grass_dense1.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_1to3
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_1to4
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_base
	
	{
		map textures/temperate_sd/grass_path1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_2to3
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base
	
	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_2to4
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base
	
	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

textures/radar_terrain_rebuild/terrain2_3to4
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_base
	
	{
		map textures/temperate_sd/rock_ugly_brown.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/dirt3.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}

// reversed 1to2
textures/radar_terrain_rebuild/terrain2_2to1
{
	q3map_baseshader textures/radar_terrain_rebuild/terrain2_foliage_base
	
	{
		map textures/temperate_sd/grass_dense1.tga
		rgbgen identity
	}
	{
		map textures/temperate_sd/grass_path1.tga
		alphaGen vertex
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
}
