// ============================================================
//
// Terrain shaders for railgun_terrain_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// Changes from original shaders:
// - removed 'q3map_lightmapsize 512 512' from 'terrain_base'
//   to allow higher resolution lightmaps
//
// ============================================================

textures/railgun_terrain_rebuild/alpha_000
{
	qer_trans 0.5
	qer_noCarve

	q3map_alphaMod volume
	q3map_alphaMod set 0.0

	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/railgun_terrain_rebuild/terrain_base
{
	q3map_lightmapMergable
	q3map_lightmapaxis z
	q3map_normalimage textures/sd_bumpmaps/normalmap_terrain.tga
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	q3map_tcMod rotate 37
	q3map_tcMod scale 1 1
	surfaceparm landmine
	surfaceparm snowsteps
}

textures/railgun_terrain_rebuild/terrain_0
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to1
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to2
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_var01_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to3
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_muddy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to4
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/mxrock4b_snow.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_noisy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_0to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_dirt_m03i_2_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1to2
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_var01_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1to3
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_muddy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1to4
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/mxrock4b_snow.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1to5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_noisy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_1to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/bigrock_rounded_faint.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_2
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_var01_big.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_2to3
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_var01_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_muddy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_2to4
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_var01_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/mxrock4b_snow.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_2to5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_var01_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_noisy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_2to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_var01_big.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_3
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_muddy.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_3to4
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_muddy.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/mxrock4b_snow.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_3to5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_muddy.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_noisy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_3to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_muddy.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_4
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/mxrock4b_snow.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_4to5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/mxrock4b_snow.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/snow_noisy.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_4to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/mxrock4b_snow.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_5
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_noisy.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_5to6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/snow_noisy.tga
		rgbgen identity
	}
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen identity
		alphaGen vertex
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}

textures/railgun_terrain_rebuild/terrain_6
{
	q3map_baseshader textures/railgun_terrain_rebuild/terrain_base
	{
		map textures/snow_sd/s_grass_ml03b_big.tga
		rgbgen identity
	}
	{
		lightmap $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbgen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
		tcMod scale 5 5
		detail
	}
}
