// ============================================================
//
// Shaders for tc_base_source_rebuild.map
// https://github.com/Aciz/et-map-source-rebuilds
//
// !!! DO NOT EDIT THIS FILE !!!
//
// ============================================================

// fixed version of stock blitz window shader, with corrected
// 'rgbGen' directive to make the windows work with 'misc_model'
textures/tc_base_source_rebuild/blitz_sd_windows_mm
{
	qer_editorimage models/mapobjects/blitz_sd/blitz_sd.tga
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/mapobjects/blitz_sd/blitz_sd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbgen environment
	}
}
